"""Renamed subject to category in Project model

Revision ID: b5c9bec026cb
Revises: 797cc39c189e
Create Date: 2025-04-13 06:00:18.271091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5c9bec026cb'
down_revision = '797cc39c189e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('end_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
